// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storeData.proto

package com.benz.online.assignment.utils;

public final class DataProtos {
  private DataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dataString = 1;</code>
     * @return The dataString.
     */
    String getDataString();
    /**
     * <code>string dataString = 1;</code>
     * @return The bytes for dataString.
     */
    com.google.protobuf.ByteString
        getDataStringBytes();

    /**
     * <code>.Data.FileType fileType = 2;</code>
     * @return The enum numeric value on the wire for fileType.
     */
    int getFileTypeValue();
    /**
     * <code>.Data.FileType fileType = 2;</code>
     * @return The fileType.
     */
    Data.FileType getFileType();

    /**
     * <code>bool isStore = 3;</code>
     * @return The isStore.
     */
    boolean getIsStore();
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      dataString_ = "";
      fileType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              dataString_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              fileType_ = rawValue;
              break;
            }
            case 24: {

              isStore_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataProtos.internal_static_Data_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataProtos.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Data.FileType}
     */
    public enum FileType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CSV = 0;</code>
       */
      CSV(0),
      /**
       * <code>XML = 1;</code>
       */
      XML(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CSV = 0;</code>
       */
      public static final int CSV_VALUE = 0;
      /**
       * <code>XML = 1;</code>
       */
      public static final int XML_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static FileType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static FileType forNumber(int value) {
        switch (value) {
          case 0: return CSV;
          case 1: return XML;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FileType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
              public FileType findValueByNumber(int number) {
                return FileType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileType[] VALUES = values();

      public static FileType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FileType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Data.FileType)
    }

    public static final int DATASTRING_FIELD_NUMBER = 1;
    private volatile Object dataString_;
    /**
     * <code>string dataString = 1;</code>
     * @return The dataString.
     */
    @Override
    public String getDataString() {
      Object ref = dataString_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataString_ = s;
        return s;
      }
    }
    /**
     * <code>string dataString = 1;</code>
     * @return The bytes for dataString.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataStringBytes() {
      Object ref = dataString_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILETYPE_FIELD_NUMBER = 2;
    private int fileType_;
    /**
     * <code>.Data.FileType fileType = 2;</code>
     * @return The enum numeric value on the wire for fileType.
     */
    @Override public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <code>.Data.FileType fileType = 2;</code>
     * @return The fileType.
     */
    @Override public FileType getFileType() {
      @SuppressWarnings("deprecation")
      FileType result = FileType.valueOf(fileType_);
      return result == null ? FileType.UNRECOGNIZED : result;
    }

    public static final int ISSTORE_FIELD_NUMBER = 3;
    private boolean isStore_;
    /**
     * <code>bool isStore = 3;</code>
     * @return The isStore.
     */
    @Override
    public boolean getIsStore() {
      return isStore_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataString_);
      }
      if (fileType_ != FileType.CSV.getNumber()) {
        output.writeEnum(2, fileType_);
      }
      if (isStore_ != false) {
        output.writeBool(3, isStore_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataString_);
      }
      if (fileType_ != FileType.CSV.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, fileType_);
      }
      if (isStore_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isStore_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Data)) {
        return super.equals(obj);
      }
      Data other = (Data) obj;

      if (!getDataString()
          .equals(other.getDataString())) return false;
      if (fileType_ != other.fileType_) return false;
      if (getIsStore()
          != other.getIsStore()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATASTRING_FIELD_NUMBER;
      hash = (53 * hash) + getDataString().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + fileType_;
      hash = (37 * hash) + ISSTORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsStore());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataProtos.internal_static_Data_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataProtos.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      // Construct using com.benz.online.assignment.utils.DataProtos.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataString_ = "";

        fileType_ = 0;

        isStore_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataProtos.internal_static_Data_descriptor;
      }

      @Override
      public Data getDefaultInstanceForType() {
        return Data.getDefaultInstance();
      }

      @Override
      public Data build() {
        Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Data buildPartial() {
        Data result = new Data(this);
        result.dataString_ = dataString_;
        result.fileType_ = fileType_;
        result.isStore_ = isStore_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data) {
          return mergeFrom((Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data other) {
        if (other == Data.getDefaultInstance()) return this;
        if (!other.getDataString().isEmpty()) {
          dataString_ = other.dataString_;
          onChanged();
        }
        if (other.fileType_ != 0) {
          setFileTypeValue(other.getFileTypeValue());
        }
        if (other.getIsStore() != false) {
          setIsStore(other.getIsStore());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object dataString_ = "";
      /**
       * <code>string dataString = 1;</code>
       * @return The dataString.
       */
      public String getDataString() {
        Object ref = dataString_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataString_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dataString = 1;</code>
       * @return The bytes for dataString.
       */
      public com.google.protobuf.ByteString
          getDataStringBytes() {
        Object ref = dataString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataString = 1;</code>
       * @param value The dataString to set.
       * @return This builder for chaining.
       */
      public Builder setDataString(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataString = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataString() {
        
        dataString_ = getDefaultInstance().getDataString();
        onChanged();
        return this;
      }
      /**
       * <code>string dataString = 1;</code>
       * @param value The bytes for dataString to set.
       * @return This builder for chaining.
       */
      public Builder setDataStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataString_ = value;
        onChanged();
        return this;
      }

      private int fileType_ = 0;
      /**
       * <code>.Data.FileType fileType = 2;</code>
       * @return The enum numeric value on the wire for fileType.
       */
      @Override public int getFileTypeValue() {
        return fileType_;
      }
      /**
       * <code>.Data.FileType fileType = 2;</code>
       * @param value The enum numeric value on the wire for fileType to set.
       * @return This builder for chaining.
       */
      public Builder setFileTypeValue(int value) {
        
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Data.FileType fileType = 2;</code>
       * @return The fileType.
       */
      @Override
      public FileType getFileType() {
        @SuppressWarnings("deprecation")
        FileType result = FileType.valueOf(fileType_);
        return result == null ? FileType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Data.FileType fileType = 2;</code>
       * @param value The fileType to set.
       * @return This builder for chaining.
       */
      public Builder setFileType(FileType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fileType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Data.FileType fileType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileType() {
        
        fileType_ = 0;
        onChanged();
        return this;
      }

      private boolean isStore_ ;
      /**
       * <code>bool isStore = 3;</code>
       * @return The isStore.
       */
      @Override
      public boolean getIsStore() {
        return isStore_;
      }
      /**
       * <code>bool isStore = 3;</code>
       * @param value The isStore to set.
       * @return This builder for chaining.
       */
      public Builder setIsStore(boolean value) {
        
        isStore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isStore = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsStore() {
        
        isStore_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Data)
    }

    // @@protoc_insertion_point(class_scope:Data)
    private static final Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data();
    }

    public static Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @Override
    public Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017storeData.proto\"k\n\004Data\022\022\n\ndataString\030" +
      "\001 \001(\t\022 \n\010fileType\030\002 \001(\0162\016.Data.FileType\022" +
      "\017\n\007isStore\030\003 \001(\010\"\034\n\010FileType\022\007\n\003CSV\020\000\022\007\n" +
      "\003XML\020\001B.\n com.benz.online.assignment.uti" +
      "lsB\nDataProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Data_descriptor,
        new String[] { "DataString", "FileType", "IsStore", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
